export enum QueryKeys {
    // category
    GET_CATEGORIES = 'GET_CATEGORIES',

    // announcement
    GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS',
    GET_ITEMS_FOR_HOME = 'GET_ITEMS_FOR_HOME',
    GET_SINGLE_ANNOUNCEMENT = 'GET_SINGLE_ANNOUNCEMENT',
    GET_ANNOUNCEMENTS_BY_CATEGORY = 'GET_ANNOUNCEMENTS_BY_CATEGORY',
}